"""encrypt_pan_aadhaar

Revision ID: 16a84df3369c
Revises: 1b6d3fa8c0af
Create Date: 2026-03-29 16:19:55.680635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import app.utils.encryption

# revision identifiers, used by Alembic.
revision: str = '16a84df3369c'
down_revision: Union[str, None] = '1b6d3fa8c0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'pan_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=app.utils.encryption.EncryptedString(length=255),
               existing_nullable=True)
    op.alter_column('employees', 'aadhaar_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=app.utils.encryption.EncryptedString(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'aadhaar_number',
               existing_type=app.utils.encryption.EncryptedString(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    op.alter_column('employees', 'pan_number',
               existing_type=app.utils.encryption.EncryptedString(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
