"""employee_geofence_fields

Revision ID: e4e1d66d8cea
Revises: 5644d4cf346a
Create Date: 2026-03-23 22:02:36.750677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e1d66d8cea'
down_revision: Union[str, None] = '5644d4cf346a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'employees', ['head_id'], ['id'], use_alter=True)
    op.add_column('employees', sa.Column('geofence_zone_id', sa.String(length=36), nullable=True))
    op.add_column('employees', sa.Column('skip_location_check', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'employees', 'geofence_zones', ['geofence_zone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'skip_location_check')
    op.drop_column('employees', 'geofence_zone_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    # ### end Alembic commands ###
